version : "2.2"
services :
    spring-boot :
        image: wlgud30/spring-shade:3.4
        ports:
               - "8080:8080"

    django :
        image : wlgud30/django-shade:1.0
        ports:
               - "8000:8000"

    react :
        image: wlgud30/react-shade:3.2
        ports:
               - "80:80"
        # volumes:
        #     - ./frontend:/usr/src/app
        #     - ./frontend/static_root:/static
        #     - /usr/src/app/node_modules
        depends_on:
            - spring-boot
            - django
